In [1]:
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [16]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [2]:
# Import the WeatherPy_vacation.csv(should be WeatherPy_challenge) file from Part 1 as a new DataFrame
part_one_city_data_df = pd.read_csv(r'weather_data/WeatherPy_challenge.csv')
part_one_city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Port Alfred,ZA,2020-01-05 21:59:38,-33.59,26.89,69.01,90,50,1.01,scattered clouds,0.00,0.0
1,1,Bluff,AU,2020-01-05 22:00:17,-23.58,149.07,74.39,77,0,10.36,clear sky,0.00,0.0
2,2,Mataura,NZ,2020-01-05 21:57:03,-46.19,168.86,52.00,72,87,25.01,light rain,1.56,0.0
3,3,Mar Del Plata,AR,2020-01-05 21:58:09,-46.43,-67.52,69.57,33,100,6.33,overcast clouds,0.00,0.0
4,4,Ushuaia,AR,2020-01-05 21:58:03,-54.81,-68.31,50.00,66,75,25.28,broken clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,555,Jinan,CN,2020-01-05 22:06:52,36.65,117.11,37.99,94,100,2.98,light rain,0.13,0.0
556,556,Akdepe,TM,2020-01-05 22:06:53,42.05,59.39,26.60,73,90,6.93,overcast clouds,0.00,0.0
557,557,Tyup,KG,2020-01-05 22:06:53,42.73,78.36,12.83,41,66,7.94,broken clouds,0.00,0.0
558,558,Antigonish,CA,2020-01-05 22:06:53,45.62,-61.99,28.99,86,90,14.99,light snow,0.00,0.0
559,559,Santana,BR,2020-01-05 22:06:53,-0.06,-51.18,78.80,100,75,5.82,broken clouds,0.00,0.0

In [3]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 70

In [4]:
# Prompt the customer to answer if he or she would like it to be raining or not, using
rain_yn = input("Do you want it to be raining? (yes/no) ")

Do you want it to be raining? (yes/no) yes

In [5]:
# Prompt the customer to answer if he or she would like it to be snowing or not, using
# Essentially yes/no could be true or false
snow_yn = input("Do you want it to be snowing? (yes/no) ")

Do you want it to be snowing? (yes/no) no

In [6]:
# Test
# test_df = False
# if part_one_city_data_df["Rain inches (last 3 hrs)"][0] > 0:
#     test_df = True
# else:
#     test_df = False
# test_df

In [7]:
# Trying to come up with a way to convert rain to a boolean value
# rain_df = False
# snow_df = False

# # Filter the dataset to find the cities that fit the criteria.
# preferred_cities_df = part_one_city_data_df.loc[(part_one_city_data_df["Max Temp"] <= max_temp) & \
#                                                 (part_one_city_data_df["Max Temp"] >= min_temp) & \
#                                                 if (part_one_city_data_df["Rain inches (last 3 hrs)"]) > 0:
#                                                     rain_df = True
#                                                 else:
#                                                     rain_df = False
#                                                 rain_df == rain_yn_tf & \
#

In [8]:
# Convert values to boolean values
rain_yn_tf = False
snow_yn_tf = False

if rain_yn == "yes":
    rain_yn_tf = True
else:
    rain_yn_tf = False

if snow_yn == "yes":
    snow_yn_tf = True
else:
    snow_yn_tf = False

In [9]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = part_one_city_data_df.loc[(part_one_city_data_df["Max Temp"] <= max_temp) & \
                                                (part_one_city_data_df["Max Temp"] >= min_temp) & \
                                                (part_one_city_data_df["Rain inches (last 3 hrs)"].astype('bool') == rain_yn_tf) & \
                                                (part_one_city_data_df["Snow inches (last 3 hrs)"].astype('bool') == snow_yn_tf)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
2,2,Mataura,NZ,2020-01-05 21:57:03,-46.19,168.86,52.00,72,87,25.01,light rain,1.56,0.0
6,6,Kruisfontein,ZA,2020-01-05 22:00:57,-34.00,24.73,65.17,83,100,5.23,light rain,0.19,0.0
15,15,Okahandja,NaN,2020-01-05 22:04:39,-21.98,16.91,66.20,77,99,5.82,light rain,0.69,0.0
82,82,Kaitangata,NZ,2020-01-05 21:59:37,-46.28,169.85,53.01,64,80,23.00,light rain,1.19,0.0
98,98,Jamestown,AU,2020-01-05 21:57:08,-33.21,138.60,56.25,87,89,5.93,light rain,2.19,0.0
168,168,Tucuman,PE,2020-01-05 22:05:18,-17.17,-70.89,63.12,50,96,12.37,light rain,0.94,0.0
224,224,Bam,IR,2020-01-05 22:05:32,29.11,58.36,56.07,79,93,17.38,moderate rain,3.44,0.0
246,246,Wamba,CD,2020-01-05 22:05:38,2.14,27.99,66.61,98,51,2.89,light rain,0.81,0.0
273,273,Grootfontein,NaN,2020-01-05 22:02:14,-19.56,18.10,65.53,91,100,8.23,moderate rain,4.25,0.0
318,318,Dunedin,NZ,2020-01-05 22:01:29,-45.87,170.50,54.00,53,39,35.99,light rain,0.56,0.0

In [24]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng","Current Description"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Current Description,Hotel Name
2,Mataura,NZ,52.00,-46.19,168.86,light rain,
6,Kruisfontein,ZA,65.17,-34.00,24.73,light rain,
15,Okahandja,NaN,66.20,-21.98,16.91,light rain,
82,Kaitangata,NZ,53.01,-46.28,169.85,light rain,
98,Jamestown,AU,56.25,-33.21,138.60,light rain,
168,Tucuman,PE,63.12,-17.17,-70.89,light rain,
224,Bam,IR,56.07,29.11,58.36,moderate rain,
246,Wamba,CD,66.61,2.14,27.99,light rain,
273,Grootfontein,NaN,65.53,-19.56,18.10,moderate rain,
318,Dunedin,NZ,54.00,-45.87,170.50,light rain,

In [25]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [26]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")

Hotel not found...skipping.

In [33]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [37]:
# Add a heatmap of temperature for the vacation spots.
# Add markers
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")