In [6]:
import pandas as pd

In [10]:
# Import the WeatherPy_vacation.csv(should be WeatherPy_challenge) file from Part 1 as a new DataFrame
part_one_city_data_df = pd.read_csv(r'weather_data/WeatherPy_challenge.csv')
part_one_city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Port Alfred,ZA,2020-01-05 21:59:38,-33.59,26.89,69.01,90,50,1.01,scattered clouds,0.00,0.0
1,1,Bluff,AU,2020-01-05 22:00:17,-23.58,149.07,74.39,77,0,10.36,clear sky,0.00,0.0
2,2,Mataura,NZ,2020-01-05 21:57:03,-46.19,168.86,52.00,72,87,25.01,light rain,1.56,0.0
3,3,Mar Del Plata,AR,2020-01-05 21:58:09,-46.43,-67.52,69.57,33,100,6.33,overcast clouds,0.00,0.0
4,4,Ushuaia,AR,2020-01-05 21:58:03,-54.81,-68.31,50.00,66,75,25.28,broken clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,555,Jinan,CN,2020-01-05 22:06:52,36.65,117.11,37.99,94,100,2.98,light rain,0.13,0.0
556,556,Akdepe,TM,2020-01-05 22:06:53,42.05,59.39,26.60,73,90,6.93,overcast clouds,0.00,0.0
557,557,Tyup,KG,2020-01-05 22:06:53,42.73,78.36,12.83,41,66,7.94,broken clouds,0.00,0.0
558,558,Antigonish,CA,2020-01-05 22:06:53,45.62,-61.99,28.99,86,90,14.99,light snow,0.00,0.0
559,559,Santana,BR,2020-01-05 22:06:53,-0.06,-51.18,78.80,100,75,5.82,broken clouds,0.00,0.0